name: App version
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: App version and push tag
      uses: anothrNick/github-tag-action@1.1.0 # Don't use @master or @v1 unless you're happy to test the latest version
      env:
        GITHUB_TOKEN: ${{ secrets.TAG_GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        WITH_V: true
