# This is a basic workflow to help you get started with Actions

name: AppVersion

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
 
  build:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v3
      - name: Create Github Release
        id: create-new-release
        uses: actions/create-release@v1.0.0
        env: 
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.rum_number }}
          
